# Generated by Django 2.2.7 on 2019-11-15 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=150)),
                ('user_DOB', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('user_Email', models.EmailField(max_length=254)),
                ('user_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
