# Generated by Django 2.2.7 on 2019-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_Name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
