# Generated by Django 2.2.7 on 2019-11-17 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20191117_1503'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='investment',
            managers=[
                ('investments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
                ('ports', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='return_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
    ]
